services:
  storage:
    image: redis
    volumes:
      - ./counter/data:/data
  counter:
    image: node:latest
    volumes:
      - ./counter:/counter
    ports:
      - 81:3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    working_dir: /counter
    depends_on:
      - storage
    command: ["npm", "run", "dev"]
  library:
    image: node:latest
    volumes:
      - ./:/app
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3001
    working_dir: /app
    depends_on:
      - counter
    command: ["npm", "run", "dev"]